# Generated by Django 2.2.1 on 2019-05-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='active',
            field=models.BooleanField(choices=[('denyLogin', '1'), ('allowLogin', '0')], default='0'),
        ),
    ]
