# Generated by Django 2.2.1 on 2019-05-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190528_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='l_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
