# Generated by Django 2.2.1 on 2019-05-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190528_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='active',
            field=models.BooleanField(default='0'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='l_time',
            field=models.DateTimeField(null=True),
        ),
    ]
