# Generated by Django 2.2.1 on 2019-05-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20190528_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='c_time',
            field=models.DateTimeField(),
        ),
    ]
