# Generated by Django 2.2.1 on 2019-06-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20190528_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='remark',
            field=models.CharField(max_length=244, null=True),
        ),
    ]
