# Generated by Django 2.2.1 on 2019-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_auto_20190609_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='Avatar',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Avatar_name',
            field=models.CharField(default='/Avatar/Avatar/cat.jpg', max_length=200),
        ),
    ]
