# Generated by Django 2.2.1 on 2019-06-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20190611_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='Avatar_name',
            new_name='Avatar',
        ),
    ]
