# Generated by Django 2.2.1 on 2019-05-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default='0')),
                ('c_time', models.DateTimeField()),
                ('l_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'doc',
                'ordering': ['c_time'],
            },
        ),
    ]
