# Generated by Django 2.2.1 on 2019-06-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0010_auto_20190611_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128)),
                ('c_time', models.DateTimeField()),
                ('m_time', models.DateTimeField(null=True)),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.UserInfo', to_field='username')),
            ],
            options={
                'db_table': 'doc',
                'ordering': ['c_time'],
            },
        ),
    ]
