# Generated by Django 2.2.1 on 2019-08-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='buy_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='urladdress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
