# Generated by Django 2.2.1 on 2019-05-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0001_initial'),
        ('Users', '0006_auto_20190528_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('content', models.CharField(max_length=128, unique=True)),
                ('tags', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField()),
                ('f_time', models.DateTimeField(null=True)),
                ('m_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=128)),
                ('doc', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wiki.doc')),
                ('username', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Users.UserInfo', to_field='username')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['c_time'],
            },
        ),
    ]
