# Generated by Django 2.2.1 on 2019-06-12 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0001_initial'),
        ('Users', '0010_auto_20190611_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tasktype', models.SmallIntegerField(choices=[(0, '不急加重'), (1, '不急'), (2, '正常'), (3, '紧急'), (4, '加急'), (5, '重要'), (6, '加重'), (7, '不急重要')], default=1, verbose_name='任务类型')),
                ('title', models.CharField(max_length=128)),
                ('description', models.FileField(null=True, upload_to='')),
                ('tags', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField()),
                ('s_time', models.DateTimeField(null=True)),
                ('f_time', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '未启动'), (1, '进行中'), (2, '完成')], default=0, verbose_name='任务状态')),
                ('doc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.doc')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.UserInfo', to_field='username')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='task_point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(null=True)),
                ('f_time', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(choices=[(0, '未启动'), (1, '进行中'), (2, '完成')], default=1, verbose_name='小任务状态')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.tasks')),
            ],
            options={
                'db_table': 'task_point',
                'ordering': ['c_time'],
            },
        ),
    ]
