# Generated by Django 2.2.1 on 2019-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tags',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
