# Generated by Django 2.2.1 on 2019-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20190615_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
