# Generated by Django 2.2.1 on 2019-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20190531_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未启动'), (2, '启动'), (3, '完成')], default=0, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tasktype',
            field=models.SmallIntegerField(choices=[(1, '不急'), (2, '正常'), (3, '紧急'), (4, '加急'), (5, '重要'), (6, '加重'), (7, '不急重要'), (8, '不急加重')], default=1, verbose_name='任务类型'),
        ),
    ]
