# Generated by Django 2.2.1 on 2019-06-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_auto_20190603_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未启动'), (1, '启动'), (2, '完成')], default=0, verbose_name='任务状态'),
        ),
    ]
