# Generated by Django 2.2.1 on 2019-06-05 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20190604_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_point',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.tasks'),
        ),
    ]
