# Generated by Django 2.2.1 on 2019-06-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_task_point_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_point',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未开始'), (2, '进行中'), (3, '结束')], default=1, verbose_name='小任务状态'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未启动'), (1, '进行中'), (2, '完成')], default=0, verbose_name='任务状态'),
        ),
    ]
