# Generated by Django 2.2.1 on 2019-06-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_auto_20190605_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task_point',
            old_name='t_time',
            new_name='f_time',
        ),
        migrations.AlterField(
            model_name='task_point',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未启动'), (1, '进行中'), (2, '完成')], default=1, verbose_name='小任务状态'),
        ),
    ]
