# Generated by Django 2.2.1 on 2019-06-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_auto_20190605_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='tasktype',
            field=models.SmallIntegerField(choices=[(0, '不急加重'), (1, '不急'), (2, '正常'), (3, '紧急'), (4, '加急'), (5, '重要'), (6, '加重'), (7, '不急重要')], default=1, verbose_name='任务类型'),
        ),
    ]
