# Generated by Django 2.2.1 on 2019-06-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_auto_20190608_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='f_time',
            new_name='s_time',
        ),
    ]
