# Generated by Django 2.2.1 on 2019-05-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelist',
            name='jumpLink',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
