# Generated by Django 2.2.1 on 2019-05-31 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
        ('Users', '0006_auto_20190528_0750'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.doc'),
        ),
        migrations.AddField(
            model_name='img',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.UserInfo', to_field='username'),
        ),
    ]
