# Generated by Django 2.2.1 on 2019-05-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20190531_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(max_length=256, upload_to=''),
        ),
    ]
