# Generated by Django 2.2.1 on 2019-05-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20190531_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='img',
            name='username',
        ),
    ]
