# Generated by Django 2.2.1 on 2019-06-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20190604_1638'),
        ('upload', '0006_auto_20190531_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.tasks'),
        ),
    ]
