# Generated by Django 2.2.1 on 2019-06-05 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_img_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='task_id',
            new_name='task',
        ),
    ]
