# Generated by Django 2.2.1 on 2019-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20190605_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='active',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
